process.chdir(__dirname);
require('dotenv').config();
const {db_} = require('./db/database');
const jwt = require('jsonwebtoken');
const secret = process.env.JWT_SECRET;
const users = db_.all('SELECT id,email,role,staff_id FROM users');
const admin = users.find(u => u.staff_id && ['admin','manager','superadmin'].includes(u.role));
const staff = users.find(u => u.staff_id && u.role === 'staff');
const AT = jwt.sign({id:admin.id,role:admin.role,staff_id:admin.staff_id},secret,{expiresIn:'2h'});
const ST = jwt.sign({id:staff.id,role:staff.role,staff_id:staff.staff_id},secret,{expiresIn:'2h'});
process.stdout.write(AT + '|' + ST + '|' + admin.staff_id + '|' + staff.staff_id + '\n');
